### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by raman-singh** [alessandrocarminati/nav#20]
Not very clear from Readme how the preconstituted DB of kernel is created initially. Is there a better explanation elsewhere which you could point to?

**Comment by alessandrocarminati** [comment]
Please look at 
https://github.com/alessandrocarminati/kern_bin_db-

**Comment by raman-singh** [comment]
Thanks. Will explore.
Can this tool be used to access the dynamic flow of calls inside kernel for a particular application? Call flow can change based on arguments to various functions. Is it possible using this or it just dumps the entire call tree?

**Comment by alessandrocarminati** [comment]
The tool aims to be a static analysis tool. Its objective is to extract all possible call flows starting from a given function. Dynamic analysis is out of scope.

**Comment by raman-singh** [comment]
ok thanks
