### ISSUE TITLE
Feature request - could output includes subsystems' info?

### ISSUE THREAD

**Issue by gianlucafarinaccio** [alessandrocarminati/nav#3]
Hi everyone,
I'm working on my project.  
In my opinion can be useful to retrieve info about subsystems for every symbol which is included in the output graph. 

Do you think is possible to get an output from nav which contains this info?
So, for me a useful output could be a JSON like this...

```js
{
  "graph": " ...dot string... ",
  "subsystems": {
     "subsystem1": ["node1", "node2"], 
     "subsystem2": ["node3", "node4", "node1"]
  }
}
```

or similar.

**Comment by alessandrocarminati** [comment]
Working on it.
